version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
